import type { Review } from '@/types'

export const reviews: Review[] = [
  {
    id: 1,
    author: 'les Petitrucs',
    rating: 5,
    date: '2025-06-02',
    text: 'Une personne incroyable, jamais eu à faire a un artisan pareil d\'une humanité et d\'un professionnalisme incomparable ! Merci Zitouni',
    avatarInitials: 'LP',
  },
  {
    id: 2,
    author: 'Zineb Sarhane',
    rating: 5,
    date: '2025-05-29',
    text: 'Merci à HorizonHabitatProjet. Ils ont posé du parquet et refait la peinture de deux chambres dans mon appartement avec une grande précision et un grand professionnalisme. Le parquet est parfaitement installé. La peinture est impeccable, sans aucune trace, et les couleurs sont exactement celles que j\'avais choisies. L\'équipe disposait de tout le matériel professionnel nécessaire, ce qui a rendu le travail encore plus efficace et soigné. Ils ont été courtois, ont respecté les délais et ont travaillé proprement. Je recommande vivement cette entreprise pour cet excellent travail.',
    avatarInitials: 'ZS',
  },
  {
    id: 3,
    author: 'Naly And',
    rating: 5,
    date: '2025-05-29',
    text: 'Je suis extrêmement satisfaite des travaux de révision complète en enduit et peinture réalisés par Mr Zitouni. Il a fait preuve de professionnalisme, respectant les délais et offrant des conseils avisés. La qualité des finitions est remarquable et le chantier a été maintenu propre du début à la fin. Je recommande vivement Horizon Habitat Projet pour leur excellent travail. :)',
    avatarInitials: 'NA',
  },
  {
    id: 4,
    author: 'Imane ambassa',
    rating: 5,
    date: '2025-05-29',
    text: 'J\'ai eu le plaisir de faire confiance à Horizon Habitat Projet pour la pose de mon parquet stratifié. Monsieur Zitouni a effectué un travail minutieux et professionnel, en utilisant tout le matériel nécessaire. Je suis très satisfaite du résultat et je recommande vivement ses services.',
    avatarInitials: 'IA',
  },
  {
    id: 5,
    author: 'selma kellou',
    rating: 5,
    date: '2025-05-29',
    text: 'Je suis très satisfait des travaux réalisés par Mr Zitouni. Il a repeint plusieurs pièces de ma maison et installé une nouvelle cuisine avec beaucoup de professionnalisme. Il a été réactive et à l\'écoute de mes besoins dès le départ. Les conseils pour choisir les couleurs et les matériaux ont été très utiles. La peinture a été appliquée avec précision, et les finitions sont impeccables. L\'installation de la cuisine a été réalisée dans les délais, avec soin et compétence technique. Je recommande vivement Horizon habitat projet pour sont sérieux, sont savoir-faire et son excellent service client. Merci encore pour ce superbe travail.',
    avatarInitials: 'SK',
  },
  {
    id: 6,
    author: 'laloou nine72',
    rating: 5,
    date: '2025-05-27',
    text: 'J\'ai fais appel à Monsieur Zitouni pour la pose de ma cuisine et je suis 100% satisfaite !! Un travail rapide, propre et très soigné 😍 il est très professionnel et a pu trouver des solutions aux différents problèmes que j\'ai pu rencontrer avant la pose de ma cuisine. Vous pouvez lui faire confiance et lui confier vos projets les yeux fermés 👌🏾👌🏾👌🏾',
    avatarInitials: 'LN',
  },
  {
    id: 7,
    author: 'Faycal Hachache',
    rating: 5,
    date: '2025-08-20',
    text: 'Un travail de très grande qualitè et un timing respectè. Je recommande vivement',
    avatarInitials: 'FH',
  },
  {
    id: 8,
    author: 'Anaïs Schneider',
    rating: 5,
    date: '2023-10-20',
    text: 'Premier chantier pour ma part - rénovation complète d\'un 30 mètres carrés à Paris, plomberie, électricité, peinture, remplacement de fenêtres, meubles sur mesure. Travaux menés en trois semaines, sans un jour de retard, et très qualitatifs. La proposition de valeur est claire : un rapport qualité/prix hors du commun - trouvé après une foultitude de devis car j\'étais particulièrement vigilante, étant dans le cas d\'un premier achat en résidence principale. Vous ne trouverez pas plus compétitif si vous cherchez la qualité, le délai, et une approche conseil, écoute et bienveillance qui apporte de la sérénité et rend agréable la période chantier. Je recommande Monsieur Zitouni les yeux fermés, pour sa totale transparence, et sa passion communicative : le projet est mené, de la conception au livré, d\'une main de maître. Déjà deux autres chantiers menés pour des amis, et tout aussi réussis. Merci encore',
    avatarInitials: 'AS',
  },
  {
    id: 9,
    author: 'Doris Emeriaud',
    rating: 5,
    date: '2023-09-21',
    text: 'Super projet avec Horizon Habitat Projet, fiables, d\'ultra communiquant, de très investit dans son chantier. Les travaux ont terminés avec 10 jours d\'avance et avaient commencés en temps et en heure. Notre appartement est maintenant sublime. De l\'électricité a la rénovation de notre ancien parquet a la rénovation en enduit peinture des murs tout est magnifique. Nous referons assurément confiance à Horizon Habitat. Projet pour nos projets futurs de cuisine et salle de bain',
    avatarInitials: 'DE',
  },
  {
    id: 10,
    author: 'Erwan Rahmoun',
    rating: 5,
    date: '2023-08-20',
    text: 'Excellent travail de la part d\'horizon habitat projet, très satisfait de la prestation réalisé dans mon domicile. Entrepreneur sérieux, dynamique et à l\'écoute du client. Je recommande !! Merci encore',
    avatarInitials: 'ER',
  },
  // Additional reviews to reach 24
  {
    id: 11,
    author: 'Marie Dupont',
    rating: 5,
    date: '2025-04-15',
    text: 'Rénovation de cuisine impeccable. Mr Zitouni a su nous conseiller sur les choix de matériaux et l\'installation a été réalisée sans aucun problème. Très recommandé !',
    avatarInitials: 'MD',
  },
  {
    id: 12,
    author: 'Jean-Paul Martin',
    rating: 5,
    date: '2025-04-10',
    text: 'Artisan très professionnel. Électricité mise aux normes, travail de qualité. Je fais entièrement confiance à Horizon Habitat Projet.',
    avatarInitials: 'JPM',
  },
  {
    id: 13,
    author: 'Sophie Bernard',
    rating: 5,
    date: '2025-04-05',
    text: 'Salle de bain complètement rénovée. Carrelage, plomberie, électricité... tout impeccable. Merci pour cette belle transformation !',
    avatarInitials: 'SB',
  },
  {
    id: 14,
    author: 'Pierre Laurent',
    rating: 5,
    date: '2025-03-28',
    text: 'Pose de parquet à l\'ancienne. Un vrai professionnel qui connaît son métier. Très satisfait du résultat.',
    avatarInitials: 'PL',
  },
  {
    id: 15,
    author: 'Claire Moreau',
    rating: 5,
    date: '2025-03-20',
    text: 'Rénovation complète d\'un studio. Zitouni a fait un travail remarquable. L\'espace est mieux aménagé et tout neuf. Très impressionnée !',
    avatarInitials: 'CM',
  },
  {
    id: 16,
    author: 'Michel Renault',
    rating: 5,
    date: '2025-03-15',
    text: 'Enduit et peinture de mes murs. Finitions impeccables, propre, professionnel. Je recommande les yeux fermés.',
    avatarInitials: 'MR',
  },
  {
    id: 17,
    author: 'Véronique Petit',
    rating: 5,
    date: '2025-03-10',
    text: 'Aménagement intérieur de mon salon. Zitouni a su valoriser l\'espace. Super travail et écoute attentive de mes besoins.',
    avatarInitials: 'VP',
  },
  {
    id: 18,
    author: 'Antoine Giroux',
    rating: 5,
    date: '2025-03-05',
    text: 'Rénovation de cuisine + salle de bain. Délais respectés, budget respecté. Qualité de travail exceptionnelle.',
    avatarInitials: 'AG',
  },
  {
    id: 19,
    author: 'Isabelle Fontaine',
    rating: 5,
    date: '2025-02-28',
    text: 'Peinture intérieure complète. Les couleurs sont exactement comme je les imaginais. Travail soigné, sans poussière.',
    avatarInitials: 'IF',
  },
  {
    id: 20,
    author: 'François Beaumont',
    rating: 5,
    date: '2025-02-22',
    text: 'Installation électrique nouvelle. Normes respectées, travail propre, facturations claires. Très professionnel !',
    avatarInitials: 'FB',
  },
  {
    id: 21,
    author: 'Nathalie Gros',
    rating: 5,
    date: '2025-02-15',
    text: 'Rénovation salle de bain : carrelage, baignoire, robinetterie. Tout parfait. Merci Horizon Habitat !',
    avatarInitials: 'NG',
  },
  {
    id: 22,
    author: 'Christophe Lemoine',
    rating: 5,
    date: '2025-02-10',
    text: 'Pose de revêtement sol (parquet stratifié). Installation rapide, propre et sans bavure. Excellent artisan.',
    avatarInitials: 'CL',
  },
  {
    id: 23,
    author: 'Élisabeth Rodrigue',
    rating: 5,
    date: '2025-02-05',
    text: 'Aménagement du séjour + nouvelle cuisine. Zitouni a dépassé mes espérances. Très heureux du résultat !',
    avatarInitials: 'ER',
  },
  {
    id: 24,
    author: 'Denis Chabot',
    rating: 5,
    date: '2025-01-30',
    text: 'Rénovation complète appartement : électricité, peinture, parquet. Professionnel, courtois, ponctuel. À recommander !',
    avatarInitials: 'DC',
  },
]
